# Data Loading

In [1]:
import pandas as pd
df=pd.read_csv(r'C:\Users\Priya\Desktop\NLP\Sarcasm.csv')

In [2]:
df

Unnamed: 0                                              tweet  \
0              0  The only thing I got from college is a caffein...   
1              1  I love it when professors draw a big question ...   
2              2  Remember the hundred emails from companies whe...   
3              3  Today my pop-pop told me I was not “forced” to...   
4              4  @VolphanCarol @littlewhitty @mysticalmanatee I...   
...          ...                                                ...   
3463        3463  The population spike in Chicago in 9 months is...   
3464        3464  You'd think in the second to last English clas...   
3465        3465  I’m finally surfacing after a holiday to Scotl...   
3466        3466  Couldn't be prouder today. Well done to every ...   
3467        3467  Overheard as my 13 year old games with a frien...   

      sarcastic  sarcasm  irony  satire  understatement  overstatement  \
0             1      0.0    1.0     0.0             0.0            0.0   
1             1      1.0    0.0     0.0             0.0            0.0   
2             1      0.0    1.0     0.0             0.0            0.0   
3             1      1.0    0.0     0.0             0.0            0.0   
4             1      1.0    0.0     0.0             0.0            0.0   
...         ...      ...    ...     ...             ...            ...   
3463          0      NaN    NaN     NaN             NaN            NaN   
3464          0      NaN    NaN     NaN             NaN            NaN   
3465          0      NaN    NaN     NaN             NaN            NaN   
3466          0      NaN    NaN     NaN             NaN            NaN   
3467          0      NaN    NaN     NaN             NaN            NaN   

      rhetorical_question  
0                     0.0  
1                     0.0  
2                     0.0  
3                     0.0  
4                     0.0  
...                   ...  
3463                  NaN  
3464                  NaN  
3465                  NaN  
3466                  NaN  
3467                  NaN  

[3468 rows x 9 columns]

In [3]:
df=df[['tweet','sarcastic']]
df

tweet  sarcastic
0     The only thing I got from college is a caffein...          1
1     I love it when professors draw a big question ...          1
2     Remember the hundred emails from companies whe...          1
3     Today my pop-pop told me I was not “forced” to...          1
4     @VolphanCarol @littlewhitty @mysticalmanatee I...          1
...                                                 ...        ...
3463  The population spike in Chicago in 9 months is...          0
3464  You'd think in the second to last English clas...          0
3465  I’m finally surfacing after a holiday to Scotl...          0
3466  Couldn't be prouder today. Well done to every ...          0
3467  Overheard as my 13 year old games with a frien...          0

[3468 rows x 2 columns]

In [4]:
df.dropna(inplace=True)

C:\Users\Priya\AppData\Local\Temp\ipykernel_828\1379821321.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)


In [5]:
df.head()

tweet  sarcastic
0  The only thing I got from college is a caffein...          1
1  I love it when professors draw a big question ...          1
2  Remember the hundred emails from companies whe...          1
3  Today my pop-pop told me I was not “forced” to...          1
4  @VolphanCarol @littlewhitty @mysticalmanatee I...          1

# Data Cleaning

In [6]:
pip install contractions

Note: you may need to restart the kernel to use updated packages.


In [7]:
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
from contractions import fix  # To handle contractions like don't -> do not
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Priya\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Priya\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Priya\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [8]:
# Initialize stopwords and lemmatizer
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def clean_text_advanced(text):
    # Expand contractions
    text = fix(text)
    
    # Remove URLs
    text = re.sub(r'http\S+', '', text)
    
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    
    # Convert to lowercase
    text = text.lower()
    
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    
    # Tokenize the text
    tokens = word_tokenize(text)
    
    # Remove stopwords and lemmatize
    cleaned_tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    
    # Join tokens back to a single string
    cleaned_text = ' '.join(cleaned_tokens)
    
    # Remove excessive whitespaces
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()
    
    return cleaned_text

df['tweet'] = df['tweet'].apply(clean_text_advanced)


C:\Users\Priya\AppData\Local\Temp\ipykernel_828\3931230.py:35: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tweet'] = df['tweet'].apply(clean_text_advanced)


In [9]:
df

tweet  sarcastic
0                  thing got college caffeine addiction          1
1     love professor draw big question mark next ans...          1
2     remember hundred email company covid started g...          1
3     today poppop told “ forced ” go college 🙃 okay...          1
4     volphancarol littlewhitty mysticalmanatee also...          1
...                                                 ...        ...
3463        population spike chicago 9 month ridiculous          0
3464  would think second last english class year pro...          0
3465  finally surfacing holiday scotland difficult d...          0
3466  could prouder today well done every student go...          0
3467  overheard 13 year old game friend smell like t...          0

[3467 rows x 2 columns]

In [10]:
df['sarcastic'].value_counts()

sarcastic
0    2600
1     867
Name: count, dtype: int64

# Data Balancing

In [11]:
from imblearn.over_sampling import RandomOverSampler

roc=RandomOverSampler(random_state=42)

X=df['tweet'].values.reshape(-1,1)
y=df.sarcastic

In [12]:
oversampler = RandomOverSampler(random_state=42)
X_balanced, y_balanced = oversampler.fit_resample(X, y)

In [13]:
df=pd.DataFrame({'tweet': X_balanced.flatten(), 'sarcastic': y_balanced})

In [14]:
df

tweet  sarcastic
0                  thing got college caffeine addiction          1
1     love professor draw big question mark next ans...          1
2     remember hundred email company covid started g...          1
3     today poppop told “ forced ” go college 🙃 okay...          1
4     volphancarol littlewhitty mysticalmanatee also...          1
...                                                 ...        ...
5195  recovered repressed memory today working kuman...          1
5196            ayeee officially “ even girl ” season 😛          1
5197  tested egg drop apartment complex fell man ’ h...          1
5198                            thinking one obsessed 💔          1
5199  funny phone start turning piece shit new iphon...          1

[5200 rows x 2 columns]

In [15]:
df['sarcastic'].value_counts()

sarcastic
1    2600
0    2600
Name: count, dtype: int64

# Vectorization and train test split

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [17]:
tfidf=TfidfVectorizer()

In [18]:
X=tfidf.fit_transform(df.tweet)

In [19]:
y = df['sarcastic']

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler(with_mean=False)
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# Model Building and evaluation

In [22]:
from sklearn.svm import SVC 
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model = SVC(kernel='linear')  # Linear kernel is common for text classification
model.fit(X_train, y_train)

SVC(kernel='linear')

In [24]:
# 4. Predictions
y_pred=model.predict(X_test)

In [25]:
y_pred

array([0, 1, 1, ..., 1, 1, 0], dtype=int64)

In [26]:
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

In [27]:
# Display results
print(f"Accuracy: {accuracy * 100:.2f}%")
print("Classification Report:\n", classification_rep)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 88.46%
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.85      0.88       493
           1       0.87      0.91      0.89       547

    accuracy                           0.88      1040
   macro avg       0.89      0.88      0.88      1040
weighted avg       0.89      0.88      0.88      1040

Confusion Matrix:
 [[420  73]
 [ 47 500]]


In [28]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=200, random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest Accuracy: {accuracy_rf * 100:.2f}%")
print("Classification Report (Random Forest):\n", classification_report(y_test, y_pred_rf))
print("Confusion Matrix (Random Forest):\n", confusion_matrix(y_test, y_pred_rf))


Random Forest Accuracy: 90.67%
Classification Report (Random Forest):
               precision    recall  f1-score   support

           0       0.89      0.92      0.90       493
           1       0.93      0.89      0.91       547

    accuracy                           0.91      1040
   macro avg       0.91      0.91      0.91      1040
weighted avg       0.91      0.91      0.91      1040

Confusion Matrix (Random Forest):
 [[454  39]
 [ 58 489]]


# Sarcasm Detection System Function

In [31]:
def detect_sarcasm(new_headline):
    clean_headline=clean_text_advanced(new_headline)
    transformed_headline=tfidf.transform([clean_headline])
    prediction = model.predict(transformed_headline)

    if prediction == 1:
        return "Sarcastic"
    else:
        return "Not Sarcastic"



In [32]:
# Example usage of detection system
test_headline = "Oh great, another Monday! I just love waking up early after the weekend."

print(f"Prediction for comment: '{test_headline}' -> \n {detect_sarcasm(test_headline)}")

Prediction for comment: 'Oh great, another Monday! I just love waking up early after the weekend.' -> 
 Not Sarcastic


In [33]:
# Example usage of detection system
test_headline = "Oh, how thoughtful! I really needed someone to explain the obvious to me."
print(f"Prediction for comment: '{test_headline}' -> \n {detect_sarcasm(test_headline)}")

Prediction for comment: 'Oh, how thoughtful! I really needed someone to explain the obvious to me.' -> 
 Not Sarcastic


# save mode and files

In [34]:
import pickle

pickle.dump(model,open("model.pkl",'wb'))
pickle.dump(tfidf,open("tfidf.pkl",'wb'))